const ActionTypes = {
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',

    ADD_PROJECT: 'ADD_PROJECT',
    SET_ACTIVE_PROJECT: 'SET_ACTIVE_PROJECT',
    SET_USER_PROJECTS: 'SET_USER_PROJECTS',

    ADD_TASK: 'ADD_TASK',
    SET_PROJECT_TASKS: 'SET_PROJECT_TASKS',
    SET_TODO_TASKS: 'SET_TODO_TASKS'
    
}

export default ActionTypes